  version: "3.8"
  services:
    servidor:
      build:
        context: ${CONTEXTO}
        dockerfile: ./dockerfiles/js/react/admin/Dockerfile
        args: 
          - CONTEXT=${CONTEXTO}
          - TZ=${TZ}
          - PROYECTO=${PROYECTO}
          - AUTOR=${AUTOR}
          
      image: ${AUTOR}/react
      container_name: ezs_react
      hostname: ${HOSTNAME}
      
      # --- TRUCO PARA QUE NO SE APAGUE ---
      tty: true
      stdin_open: true
      restart: unless-stopped
      # -----------------------------------
      
      env_file:
        - ./.env
        
      environment:
        - USUARIO=${USUARIO}
        - PASSWORD=${PASSWD}
        - CONTENEDOR=ezs_react
        
      ports:
        - "3010:3000"
        - "8810:80"
        - "${PORT_SSH}:22"
        
      volumes:
        - ./logs:/root/logs
        # VITAL: Montar el código fuente
        - ../src:/var/www/app

      networks:
        netcaronte:
          ipv4_address: 172.120.10.4

  networks:
    netcaronte:
      ipam:
        driver: default
        config:
          - subnet: 172.120.10.0/24