apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.backend.replicas | default 1 }}
  selector:
    matchLabels:
      app: poke-backend
  template:
    metadata:
      labels:
        app: poke-backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.backend.image }}
        imagePullPolicy: IfNotPresent
        command: ["node", "dist/main"]
        ports:
        - containerPort: {{ .Values.backend.port }}
        env:
        # Variables para que NestJS se conecte a Postgres
        - name: DB_HOST
          value: {{ .Values.postgres.name }}
        - name: DB_PORT
          value: "{{ .Values.postgres.port }}"
        - name: DB_USERNAME
          value: {{ .Values.postgres.user }}
        - name: DB_PASSWORD
          value: {{ .Values.postgres.password }}
        - name: DB_NAME
          value: {{ .Values.postgres.dbName }}